- name: configure {{component}}
  hosts: "{{component}}"
  become: yes
  tasks:
  - name: "Install the latest version of {{component}}"
    ansible.builtin.dnf:
      name: "{{component}}"
      state: installed

  - name: "Allow remote connections to {{component}}"
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: "start and enable {{component}}"
    ansible.builtin.service:
      name: "{{component}}"
      state: started
      enabled: yes