- name: Disable nodejs module
  ansible.builtin.command: yum module disable -y nodejs
  
- name: copy mysql repo to yum.repos.d
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable default MySQL module
  ansible.builtin.shell: yum module disable mysql -y

- name: installing mysql community server
  ansible.builtin.yum:
    name: mysql-community-server 
    state: present

- name: enabling mysql service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes 

- name: setting root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1